server:
  port: ${IEXEC_SMS_PORT:15443}
  http:
    enabled: ${IEXEC_SMS_HTTP_ENABLED:true}
    port: ${IEXEC_SMS_HTTP_PORT:15000}
  ssl:
    key-store: ${IEXEC_SMS_SSL_KEYSTORE:./src/main/resources/ssl-keystore-dev.p12} #iexec-core dev certificate for dev
    key-store-password: ${IEXEC_SMS_SSL_KEYSTORE_PASSWORD:whatever}
    key-store-type: ${IEXEC_SMS_SSL_KEYSTORE_TYPE:PKCS12}
    key-alias: ${IEXEC_SMS_SSL_KEYSTORE_ALIAS:iexec-core}
    #client-auth: need

# Not sure it's a good idea but here is a link for an embedded mongodb
# https://www.baeldung.com/spring-boot-embedded-mongodb
#spring:
#  data:
#    mongodb:
#      database: iexec-sms
#      host: ${IEXEC_SMS_MONGO_HOST:localhost}
#      port: ${IEXEC_SMS_MONGO_PORT:37017}
      #ssl-enabled: true

# Embedded H2 inside JVM
spring:
  datasource:
    url: ${IEXEC_SMS_H2_URL:jdbc:h2:file:/tmp/h2/sms-h2} # will get or create /tmp/h2/sms-h2.mv.db
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: ${IEXEC_SMS_H2_CONSOLE:true} # http://localhost:15000/h2-console/
      settings.web-allow-others: ${IEXEC_SMS_H2_CONSOLE:true} # Get console if Docker run

encryption:
  # Will get previous key or else create one on this path
  # this file shouldn't be clearly readable outside the enclave (but encrypted content could be copied outside)
  aesKeyPath: ${IEXEC_SMS_STORAGE_ENCRYPTION_AES_KEY_PATH:./src/main/resources/iexec-sms-aes.key} # /scone/iexec-sms-aes.key

blockchain:
  id: ${IEXEC_CHAIN_ID:17}
  nodeAddress: ${IEXEC_SMS_BLOCKCHAIN_NODE_ADDRESS:http://localhost:8545}
  hubAddress: ${IEXEC_HUB_ADDRESS:0xBF6B2B07e47326B7c8bfCb4A5460bef9f0Fd2002}
  gasPriceMultiplier: ${IEXEC_GAS_PRICE_MULTIPLIER:1.0} # txs will be send with networkGasPrice*gasPriceMultiplier, 4.0 means super fast
  gasPriceCap: ${IEXEC_GAS_PRICE_CAP:22000000000} #in Wei, will be used for txs if networkGasPrice*gasPriceMultiplier > gasPriceCap
  isSidechain: ${IEXEC_IS_SIDECHAIN:false}

scone:
  cas:
    host: ${IEXEC_SCONE_CAS_HOST:localhost}
    port: ${IEXEC_SCONE_CAS_PORT:8081}
    palaemon: ${IEXEC_PALAEMON_TEMPLATE:./src/main/resources/palaemonTemplate.vm}

logging:
  level:
    org.springframework: DEBUG
    org.apache.http: DEBUG
